version: "3.7"

services:
    app:
        image: symfony-app:local
        build:
            args:
                APP_ENV: "dev"
                APP_DEBUG: "1"
                PHP_IMAGE: "symfony-php:local"
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
          - .:/var/www:rw,cached

    web:
        image: symfony-web:local
        build:
            args:
                ASSETS_IMAGE: "symfony-app:local"
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 8000:80
        depends_on:
            - app
        volumes:
          - ./public:/var/www/public:ro,delegated
