version: "3.7"

services:
    app:
        image: symfony-app:local
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: app

    web:
        image: symfony-web:local
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: web
        ports:
            - 8000:80
        depends_on:
            - app
